[
 (const_declaration)
 (expression_switch_statement)
 (expression_case)
 (default_case)
 (type_switch_statement)
 (type_case)
 (for_statement)
 (func_literal)
 (function_declaration)
 (if_statement)
 (import_declaration)
 (method_declaration)
 (type_declaration)
 (var_declaration)
 (composite_literal)
 (literal_element)
 (block)
] @fold

