comment:
  layout: "header, diff, changes, uncovered"
  behavior: default  # update if exists else create new
codecov:
  branch: master
coverage:
  status:
    patch:
      default: false
    project:
      default: false  # disable the default status that measures entire project
      api:  # declare a new status context "api"
        target: 35%  # we always want 100% coverage here
        paths: "autoload/SpaceVim/api/"  # only include coverage in "tests/" folder
      leyer:  # declare a new status context "api"
        target: 35%  # we always want 100% coverage here
        paths: "autoload/SpaceVim/layers/"  # only include coverage in "tests/" folder
      plugins:  # declare a new status context "api"
        target: 35%  # we always want 100% coverage here
        paths: "autoload/SpaceVim/plugins/"  # only include coverage in "tests/" folder
      all:  # declare a new status context "app"
        paths: "!tests/"  # remove all files in "tests/"
