#!/bin/sh

DIR="$(dirname $(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )))"

cd $DIR
make pre-commit
for FILE in `git diff --staged --name-only`; do
    git add $FILE
done
