dist: xenial

language: python

python:
  - 3.6
  - 3.7

install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  - make install

script:
  - make --keep-going test lint
