" Basic mode of SpaceVim, generated by SpaceVim automatically.
let g:spacevim_enable_guicolors = 0
let g:spacevim_statusline_separator = 'nil'
let g:spacevim_statusline_inactive_separator = 'bar'
let g:spacevim_buffer_index_type = 4
let g:spacevim_enable_tabline_filetype_icon = 0


