-- Return an item that represents a time value.  The item is a
-- list with items that depend on the system.
-- The item can be passed to `reltimestr()` to convert it to a
-- string or `reltimefloat()` to convert to a Float.
-- 
-- Without an argument it returns the current "relative time", an
-- implementation-defined value meaningful only when used as an
-- argument to `reltime()`, `reltimestr()` and `reltimefloat()`.
-- 
-- With one argument it returns the time passed since the time
-- specified in the argument.
-- With two arguments it returns the time passed between {start}
-- and {end}.
-- 
-- The {start} and {end} arguments must be values returned by
-- reltime().  Returns zero on error.
-- 
-- Can also be used as a `method`: 
-- ```vim
--   GetStart()->reltime()
-- ```
-- Note: `localtime()` returns the current (non-relative) time.
--- @param start? any[]
--- @param end_? any[]
--- @return any[]
function vim.fn.reltime(start, end_) end

-- The result is a String, which is the text {string} converted
-- from encoding {from} to encoding {to}.
-- When the conversion completely fails an empty string is
-- returned.  When some characters could not be converted they
-- are replaced with "?".
-- The encoding names are whatever the iconv() library function
-- can accept, see ":!man 3 iconv".
-- Note that Vim uses UTF-8 for all Unicode encodings, conversion
-- from/to UCS-2 is automatically changed to use UTF-8.  You
-- cannot use UCS-2 in a string anyway, because of the NUL bytes.
-- 
-- Can also be used as a `method`: 
-- ```vim
--   GetText()->iconv('latin1', 'utf-8')
-- ```
--- @param string string
--- @param from string
--- @param to string
--- @return string
function vim.fn.iconv(string, from, to) end
