name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Expected behavior.
      description: What is the expected behavior?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: The reproduce ways from Vim starting.
      description: The reproduce ways are needed to debug.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Output of the `:SPDebugInfo!`
      description: Please copy and paste the result of :SPDebugInfo! command.
