name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior.
      description: What is the expected behavior?
    validations:
      required: true
  - type: textarea
    id: reproduce-step
    attributes:
      label: The reproduce ways from Vim starting.
      description: The reproduce ways are needed to debug.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: SPDebugInfo
    attributes:
      label: Output of the `:SPDebugInfo!`
      description: Please copy and paste the result of :SPDebugInfo! command.
    validations:
      required: true
