[
  (class_definition)
  (class_implementation)
  (resource_definition)
  (resource_implementation)
  (interface_definition)
  (interface_implementation)
  (for_in_loop)
  (while_statement)
  (if_statement)
  (if_let_statement)
  (elif_block)
  (struct_definition)
  (enum_definition)
  (try_catch_statement)
  (method_definition)
  (inflight_method_definition)
] @fold
