name: Semantic Pull Request Subject
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  semantic-pr-subject:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
