# the url: https://github.com/SpaceVim/SpaceVim/archive/b462646223dfb8a7b19fb3999edffd4d0dd8aea1.zip
#          https://github.com/{username}/{repo}/archive/{hash}.zip


[[repos]]
  url = 'https://github.com/'
  directory = 'trouble.nvim'
  username = 'folke'
  repo = 'trouble.nvim'
  commit = 'd99e2abd10808ef91738ce98a5c767e6a51df449'
  files = [
      'doc/trouble.nvim.txt',
  ]
