[file-run]
    command = "dir"
    isBackground = false
[file-run.options]
    cwd = '${workspaceFolder}bin/'
[test_problemMatcher]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:6:1 test error message']
    isBackground = true
[test_problemMatcher.problemMatcher]
    errorformat = ''
