cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: false

  # Enable Neovim syntax
  env:
    neovim: true

policies:
  ProhibitAutocmdWithNoGroup:
    enabled: true
  ProhibitCommandRelyOnUser:
    enabled: true
  ProhibitCommandWithUnintendedSideEffect:
    enabled: true
  ProhibitEncodingOptionAfterScriptEncoding:
    enabled: true
  ProhibitEqualTildeOperator:
    enabled: true
  ProhibitImplicitScopeBuiltinVariable:
    enabled: true
  ProhibitMissingScriptEncoding:
    enabled: true
  ProhibitNoAbortFunction:
    enabled: true
  ProhibitSetNoCompatible:
    enabled: true
  ProhibitUnnecessaryDoubleQuote:
    enabled: true
  ProhibitUnusedVariable:
    enabled: true
  ProhibitUsingUndeclaredVariable:
    enabled: true
  ProhibitAbbreviationOption:
    enabled: true
  ProhibitImplicitScopeVariable:
    enabled: true
