matrix:
  include:
    - os: linux
      env:
        - VIM_VERSION=7.4
    - os: linux
      env:
        - VIM_VERSION=8.0.0000
    - os: linux
      env:
        - VIM_VERSION=8.1.0000
    - os: linux
      env:
        - VIM_VERSION=8.2.0000
    - os: osx

sudo: false

before_script:
    - git clone https://github.com/thinca/vim-themis /tmp/vim-themis
    - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      (if ! test -d $HOME/vim-$VIM_VERSION/bin; then
       git clone https://github.com/vim/vim $HOME/vim &&
       cd $HOME/vim &&
       git checkout v$VIM_VERSION &&
       ./configure --prefix=$HOME/vim-$VIM_VERSION &&
       make &&
       make install;
       fi)
       fi
       export PATH=$HOME/vim-$VIM_VERSION/bin:$PATH
cache:
  directories:
    - $HOME/vim-$VIM_VERSION

script:
    - make
    - vim --version
    - /tmp/vim-themis/bin/themis
