source 'https://rubygems.org'
gem 'github-pages'
gem 'html-proofer'
gem 'jekyll-redirect-from', group: :jekyll_plugins
gem 'jekyll-seo-tag'
gem 'jekyll-feed'
gem 'jekyll-multiple-languages'
gem 'jekyll-paginate'
