repos:
  - repo: https://github.com/johnnymorganz/stylua
    rev: v0.17.1
    hooks:
      - id: stylua-github
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        description: Lints Lua files using Luacheck.
        entry: luacheck --
        language: system
        types: [lua]
  - repo: local
    hooks:
      - id: lighttheme
        name: Light Color Scheme Generator
        description: Ensures Light Color Scheme version has been generated.
        entry: nvim --headless -c 'source scripts/generate_colors.lua' -c 'qall'
        language: system
        types: [lua]
